##
# volume paths will be common later
# read Docker LB and 2 Tomcats to understand what this is doing
##
db:
  image: 'postgres'
  ports:
    - '5432:5432'
  expose:
    - 5432
  environment:
    POSTGRES_USER: cities_master
    POSTGRES_DB: cities

nginx:
  image: 'nginx'
  links:
    - tomcatOne:tomcat1
    - tomcatTwo:tomcat2
  volumes:
    - /home/burak/DockerVolume/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

tomcatOne:
  image: 'tomcat'
  volumes:
    - /home/burak/DockerVolume/Tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    - /home/burak/DockerVolume/Tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /home/burak/DockerVolume/Tomcat/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp

tomcatTwo:
  image: 'tomcat'
  volumes:
    - /home/burak/DockerVolume/Tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    - /home/burak/DockerVolume/Tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /home/burak/DockerVolume/Tomcat/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp