##
# volume paths will be common later
# read Docker LB and 2 Tomcats to understand what this is doing
##
nginx:
  image: 'nginx'
  links:
    - tomcatOne:tomcat1
    - tomcatTwo:tomcat2
  volumes:
    - /path/to/default.conf:/etc/nginx/conf.d/default.conf

tomcatOne:
  image: 'tomcat'
  volumes:
    - /path/to/server.xml:/usr/local/tomcat/conf/server.xml
    - /path/to/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /path/to/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp

tomcatTwo:
  image: 'tomcat'
  volumes:
    - /path/to/server.xml:/usr/local/tomcat/conf/server.xml
    - /path/to/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /path/to/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp