
db:
  image: 'postgres'
  container_name: 'postgresLocal'
  ports:
    - '5432:5432'
  expose:
    - 5432
  environment:
    POSTGRES_USER: cities_master
    POSTGRES_DB: cities

cassandra:
  image: 'cassandra:latest'
  container_name: 'cassandraLocal'
  ports:
    - '9042:9042'
    - '7199:7199'
