version: "2"
services:
  dbdev:
    image: postgres
    hostname: postgresDev
    container_name: postgresDev
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: cities_master
      POSTGRES_DB: cities
    networks:
      docker-tst:
        ipv4_address: 172.28.0.10

  cassandradev:
    image: cassandra:latest
    hostname: cassandraDev
    container_name: cassandraDev
    ports:
      - 9043:9042
      - 7200:7199
    networks:
      docker-tst:
        ipv4_address: 172.28.0.11

  kafkaserverdev:                      # includes zookeper as well
    image: spotify/kafka:latest
    container_name: kafkaDev
    hostname: kafkaDev
    ports:
      - 2184:2181
      - 9093:9092
    environment:
      ADVERTISED_HOST: kafkaserver  # hostname of zookeper
      ADVERTISED_PORT: 9092
    volumes:
      - ${PWD}/docker/kafka/logs/:/opt/kafka_2.11-0.10.1.0/logs/
      # - ${PWD}/docker/kafka/log4j.properties:/opt/kafka_2.11-0.10.1.0/config/log4j.properties
      - ${PWD}/docker/zookeeper/logs/:/var/log/zookeeper/
      - ${PWD}/docker/zookeeper/log4j.properties:/etc/zookeeper/conf/log4j.properties
    networks:
      docker-tst:
        ipv4_address: 172.28.0.12

  redisdev:
    image: redis:alpine
    container_name: redisDev
    hostname: redisDev
    ports:
      - 6380:6379
    networks:
      docker-tst:
        ipv4_address: 172.28.0.13

networks:
  docker-tst:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
