version: "2"
services:
  db:
    image: 'postgres'
    container_name: 'postgresLocal'
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_USER: cities_master
      POSTGRES_DB: cities

  cassandra:
    image: 'cassandra:latest'
    container_name: 'cassandraLocal'
    ports:
      - '9042:9042'
      - '7199:7199'

  kafkaserver:                      # includes zookeper as well
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    ports:
      - 2182:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver  # hostname of zookeper
      ADVERTISED_PORT: 9092
    volumes:
      - ${PWD}/docker/kafka/logs/:/opt/kafka_2.11-0.10.1.0/logs/
      # - ${PWD}/docker/kafka/log4j.properties:/opt/kafka_2.11-0.10.1.0/config/log4j.properties
      - ${PWD}/docker/zookeeper/logs/:/var/log/zookeeper/
      - ${PWD}/docker/zookeeper/log4j.properties:/etc/zookeeper/conf/log4j.properties