##
# volume paths will be common later
# read Docker LB and 2 Tomcats to understand what this is doing
#
# difference between expose and port:
# http://stackoverflow.com/questions/35548843/
# does-ports-on-docker-compose-yml-have-the-same-effect-as-expose-on-dockerfile
##
version: "2"
services:
  db:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: cities_master
      POSTGRES_DB: cities
    networks:
      docker-tst:
        ipv4_address: 172.28.0.20

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - 9042:9042
      - 7199:7199
    networks:
      docker-tst:
        ipv4_address: 172.28.0.19

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 83:80
    links:
      - tomcatOne:tomcat1
      - tomcatTwo:tomcat2
    volumes:
      - ${PWD}/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      docker-tst:
        ipv4_address: 172.28.0.18

  tomcatOne:
    image: tomcat:8.0-jre8
    container_name: tomcatOne
    hostname: serverone
    ports:
      - 8081:8080
    volumes:
      - ${PWD}/docker/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ${PWD}/docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ${PWD}/docker/tomcat/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp
      - ${PWD}/docker/tomcat/logs/:/usr/local/tomcat/logs/
    links:
      - db
      - cassandra
      - kafkaserver
    networks:
      docker-tst:
        ipv4_address: 172.28.0.17

  tomcatTwo:
    image: tomcat:8.0-jre8
    container_name: tomcatTwo
    hostname: servertwo
    ports:
      - 8082:8080
    volumes:
      - ${PWD}/docker/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ${PWD}/docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ${PWD}/docker/tomcat/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp
    links:
      - db
      - cassandra
      - kafkaserver
    networks:
      docker-tst:
        ipv4_address: 172.28.0.16

  kafkaserver:                      # includes zookeper as well
    image: spotify/kafka:latest
    container_name: kafka
    hostname: kafkaserver
    ports:
      - 2183:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver  # hostname of zookeper
      ADVERTISED_PORT: 9092
    volumes:
      - ${PWD}/docker/kafka/logs/:/tmp/kafka-logs/
      - ${PWD}/docker/kafka/logs/:/opt/kafka_2.11-0.10.1.0/logs/
      - ${PWD}/docker/kafka/log4j.properties:/opt/kafka_2.11-0.10.1.0/config/log4j.properties
      - ${PWD}/docker/zookeeper/logs/:/var/log/zookeeper/
      - ${PWD}/docker/zookeeper/log4j.properties:/etc/zookeeper/conf/log4j.properties
    networks:
      docker-tst:
        ipv4_address: 172.28.0.15

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

  jenkins:
    image: jenkins:latest
    container_name: jenkins
    hostname: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    networks:
      docker-tst:
        ipv4_address: 172.28.0.14

  jenkins-full:
    image: stephenreed/jenkins-java8-maven-git
    container_name: jenkinsfull
    hostname: jenkinsfull
    ports:
      - 9091:8080
    networks:
      docker-tst:
        ipv4_address: 172.28.0.21


networks:
  docker-tst:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

