##
# volume paths will be common later
# read Docker LB and 2 Tomcats to understand what this is doing
#
# difference between expose and port:
# http://stackoverflow.com/questions/35548843/
# does-ports-on-docker-compose-yml-have-the-same-effect-as-expose-on-dockerfile
##
db:
  image: 'postgres'
  ports:
    - '5432:5432'
  expose:
    - 5432
  environment:
    POSTGRES_USER: cities_master
    POSTGRES_DB: cities

cassandra:
  image: 'cassandra:latest'
  ports:
    - '7000:7000'

nginx:
  image: 'nginx'
  links:
    - tomcatOne:tomcat1
    - tomcatTwo:tomcat2
  volumes:
    - ${PWD}/dockerVolume/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

tomcatOne:
  image: 'tomcat'
  volumes:
    - ${PWD}/dockerVolume/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    - ${PWD}/dockerVolume/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ${PWD}/dockerVolume/tomcat/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp

tomcatTwo:
  image: 'tomcat'
  volumes:
    - ${PWD}/dockerVolume/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    - ${PWD}/dockerVolume/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ${PWD}/dockerVolume/tomcat/ROOT/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp